# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Dongles for cornix
  - artifact-name: cornix_dongle
    board: xiao_ble//zmk
    shield: cornix_dongle_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - artifact-name: cornix_dongle_reset
    board: xiao_ble//zmk
    shield: settings_reset
  - artifact-name: cornix_central_left
    board: cornix_left
    # shield: cornix_indicator
    # zmk studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - artifact-name: cornix_peripheral_left
    board: cornix_ph_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - artifact-name: cornix_peripheral_right
    board: cornix_right
  - artifact-name: cornix_reset
    board: cornix_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart nrf52840-nosd
